INSERT INTO carmodels (ID, TYPE, PRICE, LOYALTY_POINTS) VALUES (1, 'PREMIUM', 300, 5);
INSERT INTO carmodels (ID, TYPE, PRICE, LOYALTY_POINTS) VALUES (2, 'SUV', 150, 3);
INSERT INTO carmodels (ID, TYPE, PRICE, LOYALTY_POINTS) VALUES (3, 'SMALL', 50, 1);

INSERT INTO carbrands (ID, NAME, MODEL_ID) VALUES (1, 'BMW 7', 1);
INSERT INTO cars (ID, REGISTRATION_NUMBER, BRAND_ID) VALUES (1, '1111PPP', 1);

INSERT INTO carbrands (ID, NAME, MODEL_ID) VALUES (2, 'Kia Sorento', 2);
INSERT INTO cars (ID, REGISTRATION_NUMBER, BRAND_ID) VALUES (2, '1111SUV', 2);

INSERT INTO carbrands (ID, NAME, MODEL_ID) VALUES (3, 'Nissan Juke', 2);
INSERT INTO cars (ID, REGISTRATION_NUMBER, BRAND_ID) VALUES (3, '2111SUV', 3);

INSERT INTO carbrands (ID, NAME, MODEL_ID) VALUES (4, 'Seat Ibiza', 3);
INSERT INTO cars (ID, REGISTRATION_NUMBER, BRAND_ID) VALUES (4, '1111SSS', 4);

INSERT INTO customers(ID, ID_NUMBER) VALUES (1, '21111111Z');
INSERT INTO customers(ID, ID_NUMBER) VALUES (2, '11111111Z');